<a href="https://colab.research.google.com/github/Drisya-Ponmari/UST_INTERN/blob/master/nlp_tokenizer_Huggingface.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Overview**
Hugging Face is an NLP-focused startup with a large open-source community, in particular around the Transformers library.This helps to achieve variety of NLP tasks like text classification, information extraction, question answering, and text generation

Transformers is based around the concept of pre-trained transformer models. These transformer models come in different shapes, sizes, and architectures and have their own ways of accepting input data: via tokenization.

The library builds on three main classes: a configuration class, a tokenizer class, and a model class.
#Tokenizer Class
 The tokenizer class takes care of converting python string in arrays or tensors of integers which are indices in a model vocabulary. It has many handy features revolving around the tokenization of a string into tokens. This tokenization varies according to the model, therefore each model has its own tokenizer.

In [ ]:
#installing library
!pip install transformers

     |████████████████████████████████| 675kB 2.9MB/s 
     |████████████████████████████████| 890kB 8.7MB/s 
     |████████████████████████████████| 1.1MB 17.9MB/s 
     |████████████████████████████████| 3.8MB 24.5MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=96a02d3109e02161b92550e46227b2399bda1b917421a929c6d5a637e81286e2
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


#Tokenization with Transformer library


In [ ]:
#loading the BERT TensorFlow model as well as their tokenizers:
from transformers import (TFBertModel, BertTokenizer,
                         TFGPT2Model, GPT2Tokenizer)

bert_model = TFBertModel.from_pretrained("bert-base-cased")  # Automatically loads the config
bert_tokenizer = BertTokenizer.from_pretrained("bert-base-cased")


#tokenizing the inputs

link to the dataset information https://www.tensorflow.org/datasets/catalog/glue

In [ ]:

import tensorflow_datasets
from transformers import glue_convert_examples_to_features

data = tensorflow_datasets.load("glue/mrpc")

train_dataset = data["train"]
validation_dataset = data["validation"]

train_dataset = glue_convert_examples_to_features(train_dataset, bert_tokenizer, 128, 'mrpc')
validation_dataset = glue_convert_examples_to_features(validation_dataset, bert_tokenizer, 128, 'mrpc')
train_dataset = train_dataset.shuffle(100).batch(32).repeat(2)
validation_dataset = validation_dataset.batch(64)

INFO:absl:Overwrite dataset info from restored data version.
INFO:absl:Reusing dataset glue (/root/tensorflow_datasets/glue/mrpc/1.0.0)
INFO:absl:Constructing tf.data.Dataset for split None, from /root/tensorflow_datasets/glue/mrpc/1.0.0


In [ ]:
for i in train_dataset:
  print(i)

Streaming output truncated to the last 5000 lines.
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(32, 128), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>}, <tf.Tensor: shape=(32,), dtype=int64, numpy=
array([1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1])>)
({'input_ids': <tf.Tensor: shape=(32, 128), dtype=int32, numpy=
array([[  101,  1109,  4044, ...,     0,     0,     0],
       [  101,  1109,  1815, ...,     0,     0,     0],
       [  101,  1262,   107, ...,     0,     0,     0],
       ...,
       [  101,  1109, 20548, ...,     0,     0,     0],
       [  101,  2601,  7742, ...,     0,     0,     0],
       [  101,  1135,   112, ...,     0,     0,     0]], dtype=int3

#Hugging face tokenizer
Along with the transformers library, we @huggingface provide a blazing fast tokenization library able to train, tokenize and decode dozens of Gb/s of text on a common multi-core machine.

A Tokenizer works as a pipeline, it processes some raw text as input and outputs an Encoding. The various steps of the pipeline are:
    
    Normalizer:
     Executes all the initial transformations over the initial input string. For example when you need to lowercase some text, maybe strip it, or even apply one of the common unicode normalization process, you will add a Normalizer.
    
    PreTokenizer:
    In charge of splitting the initial input string. That's the component that decides where and how to pre-segment the origin string. The simplest example would be like we saw before, to simply split on spaces.
    
    Model:
     Handles all the sub-token discovery and generation, this part is trainable and really dependant of your input data.
    
    Post-Processor:
     Provides advanced construction features to be compatible with some of the Transformers-based SoTA models. For instance, for BERT it would wrap the tokenized sentence around [CLS] and [SEP] tokens.
    
    Decoder:
     In charge of mapping back a tokenized input to the original string. The decoder is usually chosen according to the PreTokenizer we used previously.
    
    Trainer:
     Provides training capabilities to each model.


#**TOKENSISATION PIPELINE THROUGH TOKENISER**

In [2]:
!pip install tokenizers==0.5.2

     |████████████████████████████████| 3.7MB 2.8MB/s 


In [3]:
from tokenizers import Tokenizer
from tokenizers.decoders import ByteLevel as ByteLevelDecoder
from tokenizers.models import BPE
from tokenizers.normalizers import Lowercase, NFKC, Sequence
from tokenizers.pre_tokenizers import ByteLevel

In [4]:
#creating an empty byte-pair Encoding model
tokenizer=Tokenizer(BPE.empty())

In [5]:
# Then we enable lower-casing and unicode-normalization
# The Sequence normalizer allows us to combine multiple Normalizer that will be
# executed in order.
tokenizer.normalizer = Sequence([NFKC(),Lowercase()])

In [6]:
# Our tokenizer also needs a pre-tokenizer responsible for converting the input to a ByteLevel representation.
tokenizer.pre_tokenizer = ByteLevel()

In [7]:
# And finally, let's plug a decoder so we can recover from a tokenized input to the original one
tokenizer.decoder = ByteLevelDecoder()

-----------------------------------------Overall tokenizer is now ready to be trained on the corpus-----------------------------------------------------------

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [9]:
from tokenizers.trainers import BpeTrainer


# We initialize our trainer, giving him the details about the vocabulary we want to generate
trainer = BpeTrainer(vocab_size=25000, show_progress=True, initial_alphabet=ByteLevel.alphabet())
tokenizer.train(trainer, ["/content/drive/My Drive/save/DatasetUST/big.txt"])

In [10]:
#size of the vobulary
print("Trained vocab size: {}".format(tokenizer.get_vocab_size()))

Trained vocab size: 25000


In [11]:
#saving the model
tokenizer.model.save('/content/drive/My Drive/save/DatasetUST/.')
#We now have both a `vocab.json`, which is a list of the most frequent tokens ranked by frequency, and a `merges.txt` list of merges.


['/content/drive/My Drive/save/DatasetUST/./vocab.json',
 '/content/drive/My Drive/save/DatasetUST/./merges.txt']

In [13]:
tokenizer.model = BPE.from_files('/content/drive/My Drive/save/DatasetUST/vocab.json', '/content/drive/My Drive/save/DatasetUST/merges.txt')

#INPUT
give the input string to be encoded

In [24]:
s = input()

A paragraph is used to hold information together, to let readers know that sections of text belong together. To help readers follow the meaning of the text without becoming lost or confused.  Paragraphs are facilitators and signposts. Their format is traditional and understood by most readers. So when a writer uses them incorrectly, readers will notice and can be pulled away from the fictional world. They may respond by putting down the book.


In [25]:
# Let's tokenizer a simple input
encoding = tokenizer.encode(s)

print("Encoded string: {}".format(encoding.tokens))

decoded = tokenizer.decode(encoding.ids)
print("Decoded string: {}".format(decoded))

Encoded string: ['Ġa', 'Ġparagraph', 'Ġis', 'Ġused', 'Ġto', 'Ġhold', 'Ġinformation', 'Ġtogether', ',', 'Ġto', 'Ġlet', 'Ġreaders', 'Ġknow', 'Ġthat', 'Ġsections', 'Ġof', 'Ġtext', 'Ġbelong', 'Ġtogether', '.', 'Ġto', 'Ġhelp', 'Ġreaders', 'Ġfollow', 'Ġthe', 'Ġmeaning', 'Ġof', 'Ġthe', 'Ġtext', 'Ġwithout', 'Ġbecoming', 'Ġlost', 'Ġor', 'Ġconfused', '.', 'Ġ', 'Ġparagraphs', 'Ġare', 'Ġfacilit', 'ators', 'Ġand', 'Ġsign', 'post', 's', '.', 'Ġtheir', 'Ġformat', 'Ġis', 'Ġtraditional', 'Ġand', 'Ġunderstood', 'Ġby', 'Ġmost', 'Ġreaders', '.', 'Ġso', 'Ġwhen', 'Ġa', 'Ġwriter', 'Ġuses', 'Ġthem', 'Ġincorrect', 'ly', ',', 'Ġreaders', 'Ġwill', 'Ġnotice', 'Ġand', 'Ġcan', 'Ġbe', 'Ġpulled', 'Ġaway', 'Ġfrom', 'Ġthe', 'Ġfiction', 'al', 'Ġworld', '.', 'Ġthey', 'Ġmay', 'Ġrespond', 'Ġby', 'Ġputting', 'Ġdown', 'Ġthe', 'Ġbook', '.']
Decoded string:  a paragraph is used to hold information together, to let readers know that sections of text belong together. to help readers follow the meaning of the text without becomin

In [26]:
#normalized string ((lower-casing, unicode, stripping, etc.))
print("Normalized string: {}".format(encoding.normalized_str))

Normalized string: a paragraph is used to hold information together, to let readers know that sections of text belong together. to help readers follow the meaning of the text without becoming lost or confused.  paragraphs are facilitators and signposts. their format is traditional and understood by most readers. so when a writer uses them incorrectly, readers will notice and can be pulled away from the fictional world. they may respond by putting down the book.


In [27]:
#Original string 
print("Original string: {}".format(encoding.original_str))

Original string: A paragraph is used to hold information together, to let readers know that sections of text belong together. To help readers follow the meaning of the text without becoming lost or confused.  Paragraphs are facilitators and signposts. Their format is traditional and understood by most readers. So when a writer uses them incorrectly, readers will notice and can be pulled away from the fictional world. They may respond by putting down the book.


In [28]:
#If your input has been padded by the tokenizer, then this would be a vector of 1 for any non padded token and 0 for padded ones.
print("Attention mask  of string: {}".format(encoding.attention_mask))

Attention mask  of string: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [29]:
#If your input contains special tokens such as [CLS],[SEP],[MASK],[PAD] then this would be a vector with 1 in places where a special token has been added
print("Special tokens of string: {}".format(encoding.special_tokens_mask))

Special tokens of string: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
